## Load Train Data

In [1]:
import pandas as pd
df_train = pd.read_csv('cleaned_train.csv')
df_train.head()

,responseId,view_label,ID_enter,ID_exit,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,congestion_enter_rating,congestion_exit_rating,time_segment_id,cycle_phase
0,SIsHaebOK7mfnvgPoaTSqQ0,Norman Niles #1,time_segment_5_Norman Niles #1_congestion_ente...,time_segment_5_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-05-45.mp4,2025-10-20 06:05:45,2025-10-20 06:05:45,2025-10-20 06:06:44,2025-10-20,none,free flowing,free flowing,5,train
1,EI0HadH5KqHXnvgP76fxyQI,Norman Niles #1,time_segment_6_Norman Niles #1_congestion_ente...,time_segment_6_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-06-45.mp4,2025-10-20 06:06:45,2025-10-20 06:06:45,2025-10-20 06:07:44,2025-10-20,low,free flowing,free flowing,6,train
2,A40HaYaBG8jtnvgP8NiHuAw,Norman Niles #1,time_segment_7_Norman Niles #1_congestion_ente...,time_segment_7_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-07-45.mp4,2025-10-20 06:07:45,2025-10-20 06:07:45,2025-10-20 06:08:44,2025-10-20,none,free flowing,free flowing,7,train
3,04kHacmOLrXOnvgP3YW5kQs,Norman Niles #1,time_segment_8_Norman Niles #1_congestion_ente...,time_segment_8_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-08-45.mp4,2025-10-20 06:08:45,2025-10-20 06:08:45,2025-10-20 06:09:44,2025-10-20,none,free flowing,free flowing,8,train
4,EI0HaeWIIb-envgP6uGTmAE,Norman Niles #1,time_segment_9_Norman Niles #1_congestion_ente...,time_segment_9_Norman Niles #1_congestion_exit...,normanniles1/normanniles1_2025-10-20-06-09-45.mp4,2025-10-20 06:09:45,2025-10-20 06:09:45,2025-10-20 06:10:44,2025-10-20,none,free flowing,free flowing,9,train

In [2]:
common_cols = ['responseId', 'view_label', 'videos', 'video_time', 'datetimestamp_start', 'datetimestamp_end', 'date', 'signaling', 'time_segment_id', 'cycle_phase']
df_enter = df_train[common_cols + ['ID_enter', 'congestion_enter_rating']].copy()
df_enter.rename(columns={'ID_enter': 'ID', 'congestion_enter_rating': 'congestion'}, inplace=True)
df_enter['type'] = 'enter'
print("DataFrame for 'enter' data created.")

DataFrame for 'enter' data created.

In [3]:
df_exit = df_train[common_cols + ['ID_exit', 'congestion_exit_rating']].copy()
df_exit.rename(columns={'ID_exit': 'ID', 'congestion_exit_rating': 'congestion'}, inplace=True)
df_exit['type'] = 'exit'
print("DataFrame for 'exit' data created.")

DataFrame for 'exit' data created.

In [4]:
df_train_transformed = pd.concat([df_enter, df_exit], ignore_index=True)
print("Combined DataFrame created.")

Combined DataFrame created.

In [5]:
df_train_transformed.head()

,responseId,view_label,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,time_segment_id,cycle_phase,ID,congestion,type
0,SIsHaebOK7mfnvgPoaTSqQ0,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-05-45.mp4,2025-10-20 06:05:45,2025-10-20 06:05:45,2025-10-20 06:06:44,2025-10-20,none,5,train,time_segment_5_Norman Niles #1_congestion_ente...,free flowing,enter
1,EI0HadH5KqHXnvgP76fxyQI,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-06-45.mp4,2025-10-20 06:06:45,2025-10-20 06:06:45,2025-10-20 06:07:44,2025-10-20,low,6,train,time_segment_6_Norman Niles #1_congestion_ente...,free flowing,enter
2,A40HaYaBG8jtnvgP8NiHuAw,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-07-45.mp4,2025-10-20 06:07:45,2025-10-20 06:07:45,2025-10-20 06:08:44,2025-10-20,none,7,train,time_segment_7_Norman Niles #1_congestion_ente...,free flowing,enter
3,04kHacmOLrXOnvgP3YW5kQs,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-08-45.mp4,2025-10-20 06:08:45,2025-10-20 06:08:45,2025-10-20 06:09:44,2025-10-20,none,8,train,time_segment_8_Norman Niles #1_congestion_ente...,free flowing,enter
4,EI0HaeWIIb-envgP6uGTmAE,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-09-45.mp4,2025-10-20 06:09:45,2025-10-20 06:09:45,2025-10-20 06:10:44,2025-10-20,none,9,train,time_segment_9_Norman Niles #1_congestion_ente...,free flowing,enter

## Load Test Data

In [6]:
df_test = pd.read_csv('TestInputSegments.csv')
df_test.head()

,responseId,view_label,ID_enter,ID_exit,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,congestion_enter_rating,congestion_exit_rating,time_segment_id,cycle_phase
0,7IkHaYxe2IPY-A_IpprJDA,Norman Niles #1,time_segment_112_Norman Niles #1_congestion_en...,time_segment_112_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-07-52-45.mp4,2025-10-20 07:52:45,2025-10-20 07:52:45,2025-10-20 07:53:44,2025-10-20,none,free flowing,free flowing,112,test_input_15
1,zIkHaZe0Fr-envgP6uGTmAE,Norman Niles #1,time_segment_113_Norman Niles #1_congestion_en...,time_segment_113_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-07-53-45.mp4,2025-10-20 07:53:45,2025-10-20 07:53:45,2025-10-20 07:54:44,2025-10-20,none,free flowing,free flowing,113,test_input_15
2,24wHabLnCp__698PweWaiQ4,Norman Niles #1,time_segment_114_Norman Niles #1_congestion_en...,time_segment_114_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-07-54-45.mp4,2025-10-20 07:54:45,2025-10-20 07:54:45,2025-10-20 07:55:00,2025-10-20,none,free flowing,free flowing,114,test_input_15
3,B4oHaZ3aEuK2nvgPsZGZ4Aw,Norman Niles #1,time_segment_115_Norman Niles #1_congestion_en...,time_segment_115_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-07-55-45.mp4,2025-10-20 07:55:45,2025-10-20 07:55:45,2025-10-20 07:56:44,2025-10-20,none,free flowing,free flowing,115,test_input_15
4,h4wHaYGCO-aQ2PgPqvKU8As,Norman Niles #1,time_segment_116_Norman Niles #1_congestion_en...,time_segment_116_Norman Niles #1_congestion_ex...,normanniles1/normanniles1_2025-10-20-07-56-45.mp4,2025-10-20 07:56:45,2025-10-20 07:56:45,2025-10-20 07:57:44,2025-10-20,none,free flowing,free flowing,116,test_input_15

In [7]:
common_cols = ['responseId', 'view_label', 'videos', 'video_time', 'datetimestamp_start', 'datetimestamp_end', 'date', 'signaling', 'time_segment_id', 'cycle_phase']
df_enter_test = df_test[common_cols + ['ID_enter', 'congestion_enter_rating']].copy()
df_enter_test.rename(columns={'ID_enter': 'ID', 'congestion_enter_rating': 'congestion'}, inplace=True)
df_enter_test['type'] = 'enter'
print("DataFrame for 'enter' test data created.")

DataFrame for 'enter' test data created.

In [8]:
df_exit_test = df_test[common_cols + ['ID_exit', 'congestion_exit_rating']].copy()
df_exit_test.rename(columns={'ID_exit': 'ID', 'congestion_exit_rating': 'congestion'}, inplace=True)
df_exit_test['type'] = 'exit'
print("DataFrame for 'exit' test data created.")

DataFrame for 'exit' test data created.

In [9]:
df_test_transformed = pd.concat([df_enter_test, df_exit_test], ignore_index=True)
print("Combined test DataFrame created.")

Combined test DataFrame created.

In [10]:
df_test_transformed.head()

,responseId,view_label,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,time_segment_id,cycle_phase,ID,congestion,type
0,7IkHaYxe2IPY-A_IpprJDA,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-52-45.mp4,2025-10-20 07:52:45,2025-10-20 07:52:45,2025-10-20 07:53:44,2025-10-20,none,112,test_input_15,time_segment_112_Norman Niles #1_congestion_en...,free flowing,enter
1,zIkHaZe0Fr-envgP6uGTmAE,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-53-45.mp4,2025-10-20 07:53:45,2025-10-20 07:53:45,2025-10-20 07:54:44,2025-10-20,none,113,test_input_15,time_segment_113_Norman Niles #1_congestion_en...,free flowing,enter
2,24wHabLnCp__698PweWaiQ4,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-54-45.mp4,2025-10-20 07:54:45,2025-10-20 07:54:45,2025-10-20 07:55:00,2025-10-20,none,114,test_input_15,time_segment_114_Norman Niles #1_congestion_en...,free flowing,enter
3,B4oHaZ3aEuK2nvgPsZGZ4Aw,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-55-45.mp4,2025-10-20 07:55:45,2025-10-20 07:55:45,2025-10-20 07:56:44,2025-10-20,none,115,test_input_15,time_segment_115_Norman Niles #1_congestion_en...,free flowing,enter
4,h4wHaYGCO-aQ2PgPqvKU8As,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-56-45.mp4,2025-10-20 07:56:45,2025-10-20 07:56:45,2025-10-20 07:57:44,2025-10-20,none,116,test_input_15,time_segment_116_Norman Niles #1_congestion_en...,free flowing,enter

In [11]:
df_train_features = pd.read_csv('final_merged_train_features.csv')
df_train_features.head()

,ID,time_segment_id,view_label,Direction,videos,Vehicle_Count,Avg_Speed_kmh,Max_Speed_kmh,Min_Speed_kmh,Speed_Range_kmh,Speed_Std_kmh,Avg_Brightness_Value,Day_Night_Label
0,3512_Norman_Niles_#2_entry_rating,3512,Norman Niles #2,ENTRY,normanniles2/normanniles2_2025-10-24-17-12-45.mp4,8,2.93,5.25,0.67,4.58,1.81,152.45,Day
1,3512_Norman_Niles_#2_exit_rating,3512,Norman Niles #2,EXIT,normanniles2/normanniles2_2025-10-24-17-12-45.mp4,12,5.67,7.77,0.96,6.82,2.01,152.45,Day
2,3513_Norman_Niles_#2_entry_rating,3513,Norman Niles #2,ENTRY,normanniles2/normanniles2_2025-10-24-17-13-45.mp4,11,3.18,7.29,0.73,6.56,2.24,150.86,Day
3,3513_Norman_Niles_#2_exit_rating,3513,Norman Niles #2,EXIT,normanniles2/normanniles2_2025-10-24-17-13-45.mp4,13,5.65,8.24,0.13,8.11,2.24,150.86,Day
4,3514_Norman_Niles_#2_entry_rating,3514,Norman Niles #2,ENTRY,normanniles2/normanniles2_2025-10-24-17-14-45.mp4,6,1.18,2.89,0.16,2.73,1.22,152.03,Day

In [12]:
df_train_features_processed = df_train_features.drop(columns=['ID', 'videos'])
df_train_features_processed.rename(columns={'Direction': 'type'}, inplace=True)
df_train_features_processed['type'] = df_train_features_processed['type'].str.lower()
df_train_features_processed['type'] = df_train_features_processed['type'].replace({'entry': 'enter'})
print("df_train_features_processed created and first few rows displayed.")
df_train_features_processed.head()

df_train_features_processed created and first few rows displayed.

,time_segment_id,view_label,type,Vehicle_Count,Avg_Speed_kmh,Max_Speed_kmh,Min_Speed_kmh,Speed_Range_kmh,Speed_Std_kmh,Avg_Brightness_Value,Day_Night_Label
0,3512,Norman Niles #2,enter,8,2.93,5.25,0.67,4.58,1.81,152.45,Day
1,3512,Norman Niles #2,exit,12,5.67,7.77,0.96,6.82,2.01,152.45,Day
2,3513,Norman Niles #2,enter,11,3.18,7.29,0.73,6.56,2.24,150.86,Day
3,3513,Norman Niles #2,exit,13,5.65,8.24,0.13,8.11,2.24,150.86,Day
4,3514,Norman Niles #2,enter,6,1.18,2.89,0.16,2.73,1.22,152.03,Day

In [13]:
df_train_merged = pd.merge(df_train_transformed, df_train_features_processed, on=['time_segment_id', 'view_label', 'type'], how='left')
print("Re-merged df_train_merged created and first few rows displayed.")
df_train_merged.head()

Re-merged df_train_merged created and first few rows displayed.

,responseId,view_label,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,time_segment_id,cycle_phase,...,congestion,type,Vehicle_Count,Avg_Speed_kmh,Max_Speed_kmh,Min_Speed_kmh,Speed_Range_kmh,Speed_Std_kmh,Avg_Brightness_Value,Day_Night_Label
0,SIsHaebOK7mfnvgPoaTSqQ0,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-05-45.mp4,2025-10-20 06:05:45,2025-10-20 06:05:45,2025-10-20 06:06:44,2025-10-20,none,5,train,...,free flowing,enter,1,6.30,6.30,6.30,0.00,0.00,69.66,Night
1,EI0HadH5KqHXnvgP76fxyQI,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-06-45.mp4,2025-10-20 06:06:45,2025-10-20 06:06:45,2025-10-20 06:07:44,2025-10-20,low,6,train,...,free flowing,enter,4,6.63,7.92,5.11,2.81,1.39,69.42,Night
2,A40HaYaBG8jtnvgP8NiHuAw,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-07-45.mp4,2025-10-20 06:07:45,2025-10-20 06:07:45,2025-10-20 06:08:44,2025-10-20,none,7,train,...,free flowing,enter,2,7.99,8.01,7.97,0.04,0.03,70.29,Night
3,04kHacmOLrXOnvgP3YW5kQs,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-08-45.mp4,2025-10-20 06:08:45,2025-10-20 06:08:45,2025-10-20 06:09:44,2025-10-20,none,8,train,...,free flowing,enter,1,6.71,6.71,6.71,0.00,0.00,69.44,Night
4,EI0HaeWIIb-envgP6uGTmAE,Norman Niles #1,normanniles1/normanniles1_2025-10-20-06-09-45.mp4,2025-10-20 06:09:45,2025-10-20 06:09:45,2025-10-20 06:10:44,2025-10-20,none,9,train,...,free flowing,enter,0,0.00,0.00,0.00,0.00,0.00,69.14,Night

In [14]:
df_test_features = pd.read_csv('final_merged_test_features.csv')
df_test_features.head()

,ID,time_segment_id,view_label,Direction,videos,Vehicle_Count,Avg_Speed_kmh,Max_Speed_kmh,Min_Speed_kmh,Speed_Range_kmh,Speed_Std_kmh,Avg_Brightness_Value,Day_Night_Label
0,1225_Norman_Niles_#2_entry_rating,1225,Norman Niles #2,ENTRY,normanniles2/normanniles2_2025-10-21-14-39-45.mp4,8,1.51,3.15,0.72,2.44,0.96,149.77,Day
1,1225_Norman_Niles_#2_exit_rating,1225,Norman Niles #2,EXIT,normanniles2/normanniles2_2025-10-21-14-39-45.mp4,7,7.42,10.60,4.55,6.05,2.09,149.77,Day
2,1226_Norman_Niles_#2_entry_rating,1226,Norman Niles #2,ENTRY,normanniles2/normanniles2_2025-10-21-14-40-45.mp4,11,2.01,5.33,0.23,5.10,1.73,150.62,Day
3,1226_Norman_Niles_#2_exit_rating,1226,Norman Niles #2,EXIT,normanniles2/normanniles2_2025-10-21-14-40-45.mp4,9,6.17,11.29,3.59,7.70,2.18,150.62,Day
4,1227_Norman_Niles_#2_entry_rating,1227,Norman Niles #2,ENTRY,normanniles2/normanniles2_2025-10-21-14-41-45.mp4,15,2.16,10.87,0.06,10.81,2.99,148.81,Day

In [15]:
df_test_features_processed = df_test_features.drop(columns=['ID', 'videos'])
df_test_features_processed.rename(columns={'Direction': 'type'}, inplace=True)
df_test_features_processed['type'] = df_test_features_processed['type'].str.lower()
print("df_test_features_processed created and first few rows displayed.")
df_test_features_processed.head()

df_test_features_processed created and first few rows displayed.

,time_segment_id,view_label,type,Vehicle_Count,Avg_Speed_kmh,Max_Speed_kmh,Min_Speed_kmh,Speed_Range_kmh,Speed_Std_kmh,Avg_Brightness_Value,Day_Night_Label
0,1225,Norman Niles #2,entry,8,1.51,3.15,0.72,2.44,0.96,149.77,Day
1,1225,Norman Niles #2,exit,7,7.42,10.60,4.55,6.05,2.09,149.77,Day
2,1226,Norman Niles #2,entry,11,2.01,5.33,0.23,5.10,1.73,150.62,Day
3,1226,Norman Niles #2,exit,9,6.17,11.29,3.59,7.70,2.18,150.62,Day
4,1227,Norman Niles #2,entry,15,2.16,10.87,0.06,10.81,2.99,148.81,Day

In [16]:
df_test_features_processed['type'] = df_test_features_processed['type'].replace({'entry': 'enter'})
df_test_merged = pd.merge(df_test_transformed, df_test_features_processed, on=['time_segment_id', 'view_label', 'type'], how='left')
print("df_test_merged created and first few rows displayed.")
df_test_merged.head()

df_test_merged created and first few rows displayed.

,responseId,view_label,videos,video_time,datetimestamp_start,datetimestamp_end,date,signaling,time_segment_id,cycle_phase,...,congestion,type,Vehicle_Count,Avg_Speed_kmh,Max_Speed_kmh,Min_Speed_kmh,Speed_Range_kmh,Speed_Std_kmh,Avg_Brightness_Value,Day_Night_Label
0,7IkHaYxe2IPY-A_IpprJDA,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-52-45.mp4,2025-10-20 07:52:45,2025-10-20 07:52:45,2025-10-20 07:53:44,2025-10-20,none,112,test_input_15,...,free flowing,enter,0,0.0,0.00,0.00,0.00,0.00,70.84,Night
1,zIkHaZe0Fr-envgP6uGTmAE,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-53-45.mp4,2025-10-20 07:53:45,2025-10-20 07:53:45,2025-10-20 07:54:44,2025-10-20,none,113,test_input_15,...,free flowing,enter,0,0.0,0.00,0.00,0.00,0.00,70.48,Night
2,24wHabLnCp__698PweWaiQ4,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-54-45.mp4,2025-10-20 07:54:45,2025-10-20 07:54:45,2025-10-20 07:55:00,2025-10-20,none,114,test_input_15,...,free flowing,enter,0,0.0,0.00,0.00,0.00,0.00,70.45,Night
3,B4oHaZ3aEuK2nvgPsZGZ4Aw,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-55-45.mp4,2025-10-20 07:55:45,2025-10-20 07:55:45,2025-10-20 07:56:44,2025-10-20,none,115,test_input_15,...,free flowing,enter,5,4.6,7.11,2.17,4.94,1.78,71.06,Night
4,h4wHaYGCO-aQ2PgPqvKU8As,Norman Niles #1,normanniles1/normanniles1_2025-10-20-07-56-45.mp4,2025-10-20 07:56:45,2025-10-20 07:56:45,2025-10-20 07:57:44,2025-10-20,none,116,test_input_15,...,free flowing,enter,0,0.0,0.00,0.00,0.00,0.00,70.50,Night

In [17]:
df_train_merged.to_csv('df_train_merged.csv', index=False)
df_test_merged.to_csv('df_test_merged.csv', index=False)